# name: Test Python App with uv

# on:
#   push:
#     branches:
#       - develop
#       - qt6-clean
#       - test_mac_uv
#   workflow_dispatch:

# jobs:
# #   test-windows:
# #     runs-on: windows-latest
# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v4
# #       - name: Install uv
# #         run: |
# #           pip install uv
# #       - name: Install Python 3.11 with uv
# #         run: |
# #           uv python install 3.11
# #       - name: Create venv and seed
# #         run: |
# #           uv venv --python 3.11 --seed python_venv
# #       - name: Activate venv and install package
# #         run: |
# #           .\python_venv\Scripts\Activate.ps1
# #           uv pip install .
# #       - name: Run app
# #         run: |
# #           .\python_venv\Scripts\Activate.ps1
# #           python -m GameSentenceMiner.gsm --help

# #   test-linux:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v4
# #       - name: Install uv
# #         run: |
# #           pip install uv
# #       - name: Install Python 3.11 with uv
# #         run: |
# #           uv python install 3.11
# #       - name: Create venv and seed
# #         run: |
# #           uv venv --python 3.11 --seed python_venv
# #       - name: Activate venv and install package
# #         run: |
# #           source python_venv/bin/activate
# #           uv pip install .
# #       - name: Run app
# #         run: |
# #           source python_venv/bin/activate
# #           python -m GameSentenceMiner.gsm --help

#   test-mac-311:
#     runs-on: macos-26
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Install uv
#         run: |
#           pip install uv
#       - name: Install Python 3.11 with uv
#         run: |
#           uv python install 3.11
#       - name: Create venv and seed
#         run: |
#           uv venv --python 3.11 --seed python_venv
#       - name: Activate venv and install package
#         run: |
#           source python_venv/bin/activate
#           uv pip install .
#       - name: Run app
#         run: |
#           python_venv/bin/python -m GameSentenceMiner.gsm --help > gsm_run_output.txt 2>&1
#       - name: Upload GSM run output
#         uses: actions/upload-artifact@v4
#         with:
#           name: gsm_run_output
#           path: gsm_run_output.txt
# #   test-mac-312:
# #     runs-on: macos-26
# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v4
# #       - name: Install uv
# #         run: |
# #           pip install uv
# #       - name: Install Python 3.12 with uv
# #         run: |
# #           uv python install 3.12
# #       - name: Create venv and seed
# #         run: |
# #           uv venv --python 3.12 --seed python_venv
# #       - name: Activate venv and install package
# #         run: |
# #           source python_venv/bin/activate
# #           uv pip install .
# #       - name: Run app
# #         run: |
# #           source python_venv/bin/activate
# #           python -m GameSentenceMiner.gsm --help
# #   test-mac-313:
# #     runs-on: macos-26
# #     steps:
# #       - name: Checkout repository
# #         uses: actions/checkout@v4
# #       - name: Install uv
# #         run: |
# #           pip install uv
# #       - name: Install Python 3.13 with uv
# #         run: |
# #           uv python install 3.13
# #       - name: Create venv and seed
# #         run: |
# #           uv venv --python 3.13 --seed python_venv
# #       - name: Activate venv and install package
# #         run: |
# #           source python_venv/bin/activate
# #           uv pip install .
# #       - name: Run app
# #         run: |
# #           source python_venv/bin/activate
# #           python -m GameSentenceMiner.gsm --help
